version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:16-alpine
    container_name: mobile-game-hunt-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: mobile_game_hunt_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network

  # Redis for Development
  redis:
    image: redis:7-alpine
    container_name: mobile-game-hunt-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - dev-network

  # Development Database GUI (optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: mobile-game-hunt-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mobilegamehunt.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
