name: Performance Monitoring

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  # Build and prepare for testing
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            .next/
            out/
            public/

  # Mobile Performance Testing
  lighthouse-mobile:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Start application
        run: |
          npm start &
          sleep 30

      - name: Run Lighthouse CI (Mobile)
        run: npm run lighthouse:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-mobile-reports
          path: .lighthouseci/

  # Desktop Performance Testing
  lighthouse-desktop:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Start application
        run: |
          npm start &
          sleep 30

      - name: Run Lighthouse CI (Desktop)
        run: npm run lighthouse:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-desktop-reports
          path: .lighthouseci/

  # Bundle Analysis
  bundle-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Generate bundle analysis
        run: |
          mkdir -p bundle-analysis
          npx source-map-explorer .next/static/chunks/*.js --html bundle-analysis/bundle-report.html
          npx source-map-explorer .next/static/chunks/*.js --json bundle-analysis/bundle-report.json

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: bundle-analysis/

  # Performance Summary
  performance-summary:
    runs-on: ubuntu-latest
    needs: [lighthouse-mobile, lighthouse-desktop, bundle-analysis]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate performance summary
        run: |
          echo "# Performance Test Results" > performance-summary.md
          echo "" >> performance-summary.md
          echo "## Mobile Performance" >> performance-summary.md
          echo "- Lighthouse CI completed" >> performance-summary.md
          echo "" >> performance-summary.md
          echo "## Desktop Performance" >> performance-summary.md
          echo "- Lighthouse CI completed" >> performance-summary.md
          echo "" >> performance-summary.md
          echo "## Bundle Analysis" >> performance-summary.md
          echo "- Bundle analysis completed" >> performance-summary.md
          echo "" >> performance-summary.md
          echo "## Thresholds" >> performance-summary.md
          echo "- Mobile Performance ≥ 90" >> performance-summary.md
          echo "- CLS ≤ 0.1" >> performance-summary.md
          echo "- INP P75 ≤ 200ms" >> performance-summary.md

      - name: Upload performance summary
        uses: actions/upload-artifact@v4
        with:
          name: performance-summary
          path: performance-summary.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('performance-summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
